import type { Metadata } from "next";
import "./globals.css";
import Header from "@/public/components/Header/Header";
import Footer from "../public/components/Footer/Footer"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
      <Header/>
        {children}
      <Footer/>
      </body>
    </html>
  );
}
